### ISSUE TITLE
Rename `items:` to `subtree:`

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-external-toc#27]
Right now, we use `items:` to define a single `toctree` object in a file. I think that because `items:` always maps onto one `toctree`, we should rename it simply to `subtree` so that users don't have to remember two different words.

So for example:

![image](https://user-images.githubusercontent.com/1839645/115304320-ac2fcc00-a119-11eb-98f4-07493a68461e.png)

I think that this would reduce the number of words people need to remember, and it would make it clearer that `subtrees:` always contains a list of `subtree:` lists. I think this also makes it more technically precise, because `subtree:` always maps onto a single `toctree` directive (I think)

This is making the assumption that **subtrees always contain a list of `toctree` objects**, but I think that is a correct assumption as long as we want to strictly stick with Sphinx's underlying model, right?

**Comment by choldgraf** [comment]
I think that if the `subtree` were anything other than "one of many `subtrees` in a list" then it would be confusing, but since `subtree` is always just "a list of subtree items", then `subtree` sounds more memorable and clear (to me).

**Comment by mmcky** [comment]
As you mention one nice attribute of using `subtree` is that it maps directly to the `toctree` directive which is more closely aligned with the underlying representation in `sphinx`. 

My main question is then that `subtrees` is essentially the main `toctree` (in the sphinx context). You would never nest a `subtrees` right?

**Comment by chrisjsewell** [comment]
No subtrees is not the main toctree, it is a list of toctree within a file. You can add multiple toctree directives to any file, pseudo representation:

```
subtrees:

.. toctree:
   :option: value

   items:
   doc1
   doc2

.. toctree:
   :option: value

   items:
   doc3
   doc4

```

**Comment by choldgraf** [comment]
How about we go with what Sphinx does, [and call them `entries`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree)? That is perhaps slightly more specific than `items`, is generic enough that it can contain "globs, URLs, and files", and also makes a clean mapping onto the Sphinx docs.

**Comment by mmcky** [comment]
thanks @chrisjsewell that is clear 👍

**Comment by choldgraf** [comment]
Hmm that is certainly the most similar to how it'd look if you were writing it in rst or myst

**Comment by chrisjsewell** [comment]
> is there a reason not to just use toctrees and toctree

It just feels abit weird to me, with respect to terminology, since essentially the whole file is the ToC tree, then (as shown in https://github.com/executablebooks/sphinx-external-toc/blob/main/toc-graphic.png) the `subtrees` are just that; sub-components of the whole tree.
Then for `toctree`, this key doe not specify everything about the toctree, i.e. its options, merely the list of item/entries in it
