### ISSUE TITLE
Should `jb-book` be defined in this package, or in Jupyter Book?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-external-toc#30]
This package defines an extension point where we can define new schemas for parsing TOC structures, and it comes with two non-defaults out of the box (jb-book and jb-article). E.g.:

https://github.com/executablebooks/sphinx-external-toc/blob/fdfac04fb54d0b6f295eec27aaf6399df7851a55/sphinx_external_toc/tools.py#L340

I am wondering if instead we should define a way for authors to create their own extensions, and then `jupyter-book` (the package) would be where `jb-book` and `jb-article` are defined. This might make this extension less "jupyter-book specific".

I don't think this is a blocker for an initial release, but curious if others think this is a reasonable idea.

**Comment by chrisjsewell** [comment]
Maybe, but yeh not until the package is solidified. 
Also one of the points of this is kinda to move jupyter-book away from really implementing any new code; such that it's just an aggregation of sphinx extensions that people can use directly if they wish. Having to install jupyter-book (and this all its dependencies) to access these formats might not then be ideal

**Comment by choldgraf** [comment]
closing this since we can spot-check it in the future
