### ISSUE TITLE
Sphinx 6 support

### ISSUE THREAD

**Issue by Vorensics** [executablebooks/sphinx-external-toc#90]
### Context

I tried to update Sphinx and sphinx_external_toc via pip-review. However, external_toc version 0.3.1. seems to be incompatible to Sphinx >= 6. It is producing the error:

`sphinx-external-toc 0.3.1 requires sphinx<6,>=4, but you have sphinx 6.1.3 which is incompatible.`

### Proposal

Please add compatibility to Sphinx >=6.

### Tasks and updates

Please add compatibility to Sphinx >=6.

**Comment by georgkrause** [comment]
@Vorensics Did you tried patching the restriction away already? Is there any actual hard dependency on sphinx <6 in the code?

**Comment by agoose77** [comment]
Closed by #97
